version: '2.0'
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.centos
    ports:
    - "8080:8080"
    volumes:
    - ./airflow.cfg:/opt/airflow/airflow.cfg
    environment:
      - DB_USER=airflow
      - DB_PASSWORD=q1
      - DB_HOST=mysql
    depends_on:
    - mysql
    networks:
      - default
  mysql:
    image: mariadb:10
    restart: always
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=TRUE
    environment:
      - MYSQL_ROOT_PASSWORD=q1
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=q1
    networks:
      default:
        aliases:
          - mysql
    cap_add:
      - SYS_NICE
networks:
  default:
