version: '2.0'
services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.centos
    ports:
    - "8080:8080"
    volumes:
    - ./airflow.cfg:/opt/airflow/airflow.cfg
    depends_on:
    - mysql
    networks:
      - default
  mysql:
    image: mariadb:5.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=q1
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=q1
    networks:
      default:
        aliases:
          - mysql
    cap_add:
      - SYS_NICE
networks:
  default:
