#!/bin/bash
until echo "exit" | mysql -uairflow -pq1 -h mysql airflow; do
  echo "---===### Database is unavailable - sleeping ###===---"
  sleep 1
done
echo "---===### Databse is up - Initializing ###===---"
airflow initdb
echo "---===### Starting Airflow Scheduler ###===---"
airflow scheduler &
echo "---===### Starting Airflow Worker ###===---"
airflow worker &
echo "---===### Starting Airflow Webserver ###===---"
airflow webserver
